name = "rentifier-processor"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "rentifier"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "../../packages/db/migrations"
